name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 2.2.2
authors:
  - Jimmy Aumard <jimmy.aumard@gmail.com>
  - Rushio Consulting <dev@rushio-consulting.fr>
repository: https://github.com/rushio-consulting/flutter_camera_ml_vision
homepage: https://rushio-consulting.fr

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_ml_vision: ^0.8.0+3
  path_provider: ^1.4.2
  pedantic: ^1.8.0+1
  device_info: ^0.4.1+1
  camera:
    git:
      url: 'git@github.com:NeKoFu/plugins.git'
      path: 'packages/camera'
      ref: 'camera_torch'

dev_dependencies:
  flutter_test:
    sdk: flutter
    